import { SignInButton, SignedIn, SignedOut, UserButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import { JSXElementConstructor, Key, PromiseLikeOfReactNode, ReactElement, ReactNode, ReactPortal, use } from "react";

import { RouterOutputs, api } from "~/utils/api";


const CreatePostWizard = () => {
  const { user } = useUser();

  if (!user) {
    return null;
  }

  return (
    <div className="flex gap-3 w-full">
      <UserButton afterSignOutUrl="/" />
      <input placeholder="Emoji something" className="bg-transparent grow outline-none" />
    </div>
  );
}

export default function Home() {
  const { data, isLoading } = api.post.getAll.useQuery();

  if (isLoading) {
    return (
      <div className="flex justify-center h-screen">
        <div className="text-2xl">Loading...</div>
      </div>
    );
  }

  if (!data) {
    return (
      <div className="flex justify-center h-screen">
        <div className="text-2xl">Something went wrong...</div>
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="w-full md:max-w-2xl border-x border-slate-400">
          <div className="flex align-right border-b border-slate-400 p-4 flex">
            <SignedIn>
              <CreatePostWizard />
            </SignedIn>
            <SignedOut>
              {/* Signed out users get sign in button */}
              <SignInButton />
            </SignedOut>
          </div>
          <div className="flex flex-col">
            {data?.map((post) => (
              <div key={post.id} className="border-b border-slate-400 p-4">
                {post.content}
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
