import { SignInButton, SignedIn, SignedOut, UserButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Image from "next/image";

import { RouterOutputs, api } from "~/utils/api";

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";

dayjs.extend(relativeTime);

// component for creating a post
const CreatePostWizard = () => {
  const { user } = useUser();

  return (
    <div className="flex gap-3 w-full">
      <UserButton afterSignOutUrl="/" />
      <input placeholder="Emoji something" className="bg-transparent grow outline-none" />
    </div>
  );
};

const UserPostTopBar = () => {
  return (
    <>
      <div className="flex align-right border-b border-slate-400 p-4 flex">
        <SignedIn>
          <CreatePostWizard />
        </SignedIn>
        <SignedOut>
          {/* Signed out users get sign in button */}
          <SignInButton />
        </SignedOut>
      </div>
    </>
  )
};

type PostWithAuthor = RouterOutputs["post"]["getAll"][0];

// component for viewing a post
const PostView = (props: PostWithAuthor) => {
  const { post, author } = props;

  return (
    <div key={post.id} className="border-b border-slate-400 p-8 flex gap-2 flex-row">
      <div className="flex flex-col justify-center">
        <Image
          src={author.imgUrl}
          className="w-8 h-8 rounded-full justify justify-center"
          alt={`@${author.username}'s profile image`}
          width={32}
          height={32}
          // placeholder="blur"
          // blurDataURL="default-avatar.png"
        />
      </div>

      <div className="flex flex-col justify-center text-slate-500">
      </div>

      <div className="flex-grow flex flex-col justify justify-center">
        <div className="flex gap-1 text-slate-300">
          <span>
            {`@${author.username}`}
          </span>
          <span className="mx-2">·</span>
          <span>
            {dayjs(post.createdAt).fromNow()}
          </span>
        </div>
        <div className="flex">
          {post.content}
        </div>
      </div>
    </div>
  );
}


// Homepage
export default function Home() {
  const user = useUser();
  const { data, isLoading } = api.post.getAll.useQuery();

  if (isLoading) {
    return (
      <main className="flex justify-center h-screen">
        <div className="w-full md:max-w-2xl border-x border-slate-400">
          <UserPostTopBar />
          <div >
          </div>
          <div className="flex flex-col p-8">
            Loading...
          </div>
        </div>
      </main>
    );
  }

  if (!data) {
    return (
      <main className="flex justify-center h-screen">
        <div className="w-full md:max-w-2xl border-x border-slate-400">
          <UserPostTopBar />
          <div className="flex flex-col p-8">
            Error loading posts...
          </div>
        </div>
      </main>
    );
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="w-full md:max-w-2xl border-x border-slate-400">

          <UserPostTopBar />

          <div className="flex flex-col">
            {data?.map((postWithAuthor) => (
              <PostView {...postWithAuthor} key={postWithAuthor.post.id} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
